session_name: "LavaStudio"
lifetime: 3600 #session expires in 10min if left idle
path: /
domain: "localhost"
secure: false
httponly: true
gc_maxlifetime: "1800"
gc_probability: "1000"
gc_divisor: "1"
use_cookies: "1"
drivers:
  default_storage:
    class: \MagmaCore\Session\Storage\NativeSessionStorage
    alias: native_storage
    default: true
globalized: false
