services:
  subscribers:
    base_controller_action.subscriber:
      class: \MagmaCore\Base\EventSubscriber\BeforeControllerActionSubscriber
    base_render_action.subscriber:
      class: \MagmaCore\Base\EventSubscriber\BeforeRenderActionSubscriber
    system_action_event:
      class: \MagmaCore\System\Subscriber\SystemActionSubscriber
    controllerSettings.subscriber:
      class: \MagmaCore\Settings\EventSubscriber\ControllerSettingActionSubscriber